#include <a_samp>
#include <a_mysql>
#include <bcrypt>

/*
 * ---------------------------------------------------------
 * Variables und Info Part
 * ---------------------------------------------------------
 */

#include <../../include/Info/mysql_data>
#include <../../include/preprocess>
#include <../../include/Info/GlobalStructs>
#include <../../include/mysql_init>
#include <../../include/Pools/Player>

/*
 * ---------------------------------------------------------
 * Systems Part
 * ---------------------------------------------------------
 */
 
#include <../../include/Systems/Login>